name: ABAPLint Checks

on: [push, pull_request]

jobs:
  abaplint:
    runs-on: ubuntu-latest
    name: ABAPLint
    steps:
    - uses: actions/checkout@v1
    - name: abaplint Action
      uses: abaplint/actions-abaplint@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
