name: ABAPLint Checks

on:
  pull_request:
  push:
      branches:
        - master

jobs:
  abaplint:
    runs-on: ubuntu-latest
    name: ABAPLint
    steps:
    - uses: actions/checkout@v2
    - name: abaplint Action
      uses: abaplint/actions-abaplint@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
